### ISSUE TITLE
Steps to get it working

### ISSUE THREAD

**Issue by pablofr918** [paclema/esp32_lwip_nat_example#1]
Hi @paclema, I'm trying to follow your steps to have this working on platformio. I have built the libraries with NAT enabled, and now I have to use this libraries in Platformio. This is where I get lost because I haven't used PlatformIO before. You say that there is a folder /packages in C:/user.../.platformio, but I don't have this folder, do you know if there is something to do first to get this configured?

**Comment by pablofr918** [comment]
I have cloned your repo and compiled, but this error appears: 
_In file included from src/main.cpp:1:
C:/.platformio/packages/framework-arduinoespressif32/cores/esp32/Arduino.h:188:10: fatal error: pins_arduino.h: No such file or directory_ 
Did this happen to you?

**Comment by pablofr918** [comment]
I got it! Thank you so much! I really apreciate you put this in github!! <3

**Comment by paclema** [comment]
Hi @pablofr918 I am happy to hear that you find the solution :) It seems that you had not configured PlatformIO correctly before. I recommend you to use it rather than Arduino IDE if you want to have better control with each version for your libraries.
I am also happy that you found it useful, thank you! <3

**Comment by pablofr918** [comment]
@paclema I have a question, where do you have the arduino-esp32 libs modified? Because if I look in here: _https://github.com/paclema/arduino-esp32/releases_ I can't find a version with the lwip_nat.h, only the 2.0.0, but I don't know if it is the modified version with nat enabled. This is just to start understanding things!

**Comment by paclema** [comment]
There is not release created to download. You can check this platformio configuration for this example: https://github.com/paclema/esp32_lwip_nat_example/blob/main/platformio.ini#L23 . It defines where is the arduino-esp32 framework that should be used. In this case, under my other repo in the branch _lwip_enabled_. Platformio will download and install it to compile the code automatically.

**Comment by pablofr918** [comment]
Hello @paclema, I'm trying to use more things that must be compiled from idf, so could you tell me the way you compiled the esp32 framework in order to enable other features like Bluedroid? I tried it before but I can´t get the last steps, when I get the compiled folder, I try to replace it with the original one and a lot of errors appear.

**Comment by paclema** [comment]
Hi @pablofr918 I am sorry that I don't have so much experience with that. This is the first and only case where I have compiled idf. I can only suggest you to take specially care of the idf version and arduino esp32 framework you are using. You must recompile idf using the same idf version that is used in the esp32 arduino framework that you are going to use or you will have such errors.

**Comment by pablofr918** [comment]
Okay, no problem. I'll ask you some things as soon as I get improvements so in case you remember you can help me. For example, I have just compiled the idf with custom configuration in menuconfig (as I supose you did for enabling the NAT). But now, if I want to use the framework with this new configuration in Platformio, as you did, what will be the next step? To get some folders from there and put in other place?

**Comment by pablofr918** [comment]
I mean, in your repo, when you say the following:

**_It will be exported under esp32-arduino-lib-builder/dist a .gz file containning the libs that it should be placed under framework-arduinoespressif32 folder that you can find under C:\Users\<your-user>\.platformio\packages\_**

where do I find that folder containning the libs to replace?

Thank you very much for your support!
