### ISSUE TITLE
how to get full speed

### ISSUE THREAD

**Issue by irwanayeah** [paclema/esp32_lwip_nat_example#2]
Hi @paclema,

finally my esp was successfully activated as a wifi extender using the arduino framework, the maximum test results were 2Mbps.
my question is how to make it full speed as per specs around 15Mbps?
what parameters should be changed in order to make it fullspeed. Thank you very much.

**Comment by paclema** [comment]
Hi @irwanayeah, I am sorry for the late response. 

Anyway, I am not able to help you here. This is repo is just an example of how to enable this feature, by compiling your own Arduino framework, but I am afraid to not know enough about this topic to be able to help you. 

I hope that your findings worked!

**Comment by georgie3** [comment]
I am able to get top download speed of about 10 Mbps with this code using Arduino IDE and ESP32 without optimizing anything. Note that if you have a Chinese ESP32 board with CH340 USB chip try powering the board with 5V on Vin pin (and of course ground connected), with USB port disconnected, to increase WiFi speed.
