### ISSUE TITLE
Deep Sleep Examples not working as expected

### ISSUE THREAD

**Issue by Oopas** [paclema/esp32_lwip_nat_example#4]
After using the libs you uploaded, I found that esp32 cannot wake up through the touchpad or RTCIO after deep sleep.

**Comment by Oopas** [comment]
But when I recompile the latest source code according to your steps, I can wake up esp32 from deep sleep through the touchpad or RTCIO very smoothly.

**Comment by paclema** [comment]
I am happy that it worked! I close then this issue
