### ISSUE TITLE
Compilation error: 'dhcpSoftAP' was not declared in this scope

### ISSUE THREAD

**Issue by blackleakz** [paclema/esp32_lwip_nat_example#5]
[https://github.com/paclema/esp32_lwip_nat_example/blob/main/src/main.cpp](url)

what i need to do to declare?

**Comment by paclema** [comment]
I assusme that you are trying to follow this example to compile your program for an ESP8266 board.

Looking on the Arduino core for ESP8266 repo, It seems that they removed last June the declaration of this SoftAP DhcpServer object within this commit: https://github.com/esp8266/Arduino/commit/502d9469fa022a5ce942bc2f2940f42699664ef7

So now, if what you want is to provide the DNS to the AP side, instead to use those lines:

```c
 dhcpSoftAP.dhcps_set_dns(0, WiFi.dnsIP(0));
 dhcpSoftAP.dhcps_set_dns(1, WiFi.dnsIP(1));
```

You need to include `LwipDhcpServer.h` and change the above lines with those ones:

```c
  auto& server = WiFi.softAPDhcpServer();
  server.setDns(WiFi.dnsIP(0));
```

You can also take a look to this [RangeExtender-NAPT](https://github.com/esp8266/Arduino/tree/master/libraries/ESP8266WiFi/examples/RangeExtender-NAPT) example for more information. For ESP8266 this feature is enabled by default, the example code of this repo illustrates the equivalent procedure if you use an ESP32 instead. 

I have modified this repo example adding this change on this commit: https://github.com/paclema/esp32_lwip_nat_example/commit/f329c5845c353a3ea5aa1b5d3331a1caa6e6b0ae
Thank you for pointing out this new change!
